### ISSUE TITLE
Arrow rendering can be when an arrow enters and exits a number on the same side

### ISSUE THREAD

**Issue by JoshMermel** [ambuc/juggling-graph#3]
For example, on the input "1263", an arrow enters the 2 from the top and another exits the 2 from the top. Also an arrow enters the 6 on the bottom and another exits the 6 on the bottom. It would be nice if the arrow rendering made it clearer which direction these arrows were going.

**Comment by ambuc** [comment]
Fixed in 43c69c79988515ed38e0f4513c00671a48ad02b5.

**Comment by ambuc** [comment]
Regressed as of #9.

**Comment by ambuc** [comment]
Re-fixed as of #11
