### ISSUE TITLE
Consider a cap on input length

### ISSUE THREAD

**Issue by JoshMermel** [ambuc/juggling-graph#6]
In the current version, character and arrows bunch up and become unreadable when the length of the input is too long. It might be better to cap the input length than have a bad user experience.

**Comment by ambuc** [comment]
I like this idea. Right now the arrow conflict resolution implementation means that arrows of jump 1 render weird on a dense siteswap. I'll set a maxLength at 20 for now and revisit if we decide to make this more extensible, or not locked in a canvas.

**Comment by ambuc** [comment]
Resolved in 0e63d3b6cb64d692e48b83948a4c87f046c64e22.
